spring:
  application:
    name: bank-monolith

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://us-cdbr-iron-east-04.cleardb.net/ad_f4803d940cc9b7c?user=b641e6832221d9\u0026password=39498590
    username: b641e6832221d9
    password: 39498590
    tomcat:
      max-active: 2
  jpa:
    hibernate.ddl-auto: none
    show_sql: true

server:
  port: ${PORT:8181}
